name: Vue project Build and Deploy
on:
    push:
        branches:
            - master # 当master分支有变更，则执行以下jobs操作
jobs:
    deploying_vue_project:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2.3.1
              with:
                  persist-credentials: false
            - name: building
              # 执行shell命令
              run: |
                  npm install
                  npm run build
            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@4.1.5
              with:
                  branch: master
                  folder: dist
                  token: ${{ secrets.ACCESS_TOKEN }}
                  repository-name: AutumnWhj/AutumnWhj.github.io # github page 仓库
                  target-folder: github-actions-docs
